name: Publish Workflow
'on':
  workflow_run:
    workflows:
    - Release Workflow
    types:
    - completed
permissions:
  contents: read
run-name: Publish Workflow
defaults:
  run:
    shell: bash
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Setup Git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.14.0
    - name: Setup Poetry
      uses: snok/install-poetry@main
      with:
        version: latest
    - name: Configure Poetry with PyPI Token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - name: Build and publish to PyPI
      run: poetry publish --build
